### PR TITLE
multiplayer fix

### PR DESCRIPTION
**Pull request by darksody**
Added a mechanism to get the game directory from console input (or via a file called "path_to_game.txt").
Attention, the directory only, not the exe.

Will then detect the "Game.exe" file and rename it upon each run of the program to "Game{0}.exe", the number being incremented upon each execution.

The reason for it is to enable the multiplayer button. Not sure where does it cache it, but if you rename it once, it works. Second run of the program it doesn't, so needs renaming again.

### CODE REVIEW

**Comment by ferib** [comment]
I am afraid this has nothing to do with 'fixing' the actual thing.
The trick is the timing, I have been working on a way to hook the entry point so I can smoosh in my patch **right before** the function gets executed but **right after** the game is unpacked.

My previous attempts have failed due to some additional checks that are performed at startup, so keep an eye out here for a fix on this problem.

**Comment by ferib** [comment]
This does not mean your efforts aren't valued, if this helps for you and/or other people then make sure to keep those changes to your GitHub ;D

**Comment by ferib** [comment]
UPDATE: this timing issues should now have been fixed in commit https://github.com/ferib/D2R-Offline/commit/f8fff5e9c7456dffea989953469d3e4e4e6cdb41

**Comment by darksody** [comment]
Nice one, it works.

**Pull request closed without merging**
